name: Python CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkoutav2
      - uses: actions/ setup-pythonav2
        with:
          python-version: '3.9'
      - run: pip install -r requirements.txt
      - run: pytest